### ISSUE TITLE
Group Project Assignment 

### ISSUE THREAD

**Issue by Mithi-code** [Mithi-code/ruby-capstone#1]
Please find a below link to our project 
[Project](https://github.com/Mithi-code/ruby-capstone/projects/1)

Group members

1. @Mithi-code
2. @roshan-bajgain 
3. @matovu-farid 
4. @rachidelaid

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @rachidelaid, @Mithi-code, @matovu-farid and @roshan-bajgain,

Good job so far!
✔️ Kanban columns are well set up
✔️ Assignment of tasks
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Team member 4 (@rachidelaid) is missing the following tasks. Kindly add them.

  ![rachid-tasks](https://user-images.githubusercontent.com/36542986/163788330-bbe5a2de-1186-41a1-aef9-549234ebdf77.jpg)
- [ ] Team member 2 (@roshan-bajgain) is missing the following task. Kindly add that.

  ![roshan-1](https://user-images.githubusercontent.com/36542986/163788240-75a6d6ef-a9d5-481d-9a60-1c2b8816cf36.jpg)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @rachidelaid, @Mithi-code @matovu-farid and @roshan-bajgain,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
